# Generated by scripts/update-homebrew-formula.sh from release cli-v1.0.0.
# Do not edit by hand — re-run the script against a new release tag.
class Line9 < Formula
  desc "Diagrams for thinking — render Mermaid diagrams from the CLI"
  homepage "https://line9.ai"
  version "1.0.0"
  # Proprietary; the binary is not open source. See the tap LICENSE.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v1.0.0/line9-cli-v1.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "a8704279558178fdde8f582fce40ee9382984d484c47da0919a533417e458405"
    end
    on_intel do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v1.0.0/line9-cli-v1.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "237e64d0e28f477fcb7498888bcb27943579841d79e48962afe0e52f39da22ba"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v1.0.0/line9-cli-v1.0.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "25f5ed4894af8d6c53eaa02cd54cd29b0a96da1fe39df3ae58da7c84e47cc324"
    end
    on_intel do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v1.0.0/line9-cli-v1.0.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "105d7f0feb3bfad1e6a36c885b9efda739eeb8a430db1e1a881ab0167f828504"
    end
  end

  def install
    # The archive's single top-level dir (line9-<tag>-<target>/) holds the
    # binary; Homebrew auto-changes into it on unpack, so install from the root.
    bin.install "line9"
    # Dynamic shell completion (JUM-564):  emits the
    # re-invocation shim; brew places it on fpath / bash_completion.d so TAB
    # works with zero user steps. Same script part 1 and part 2 share.
    generate_completions_from_executable(bin/"line9", "completions", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/line9 --version")
  end
end
