# Generated by scripts/update-homebrew-formula.sh from release cli-v0.3.2.
# Do not edit by hand — re-run the script against a new release tag.
class Line9 < Formula
  desc "Diagrams for thinking — render Mermaid diagrams from the CLI"
  homepage "https://line9.ai"
  version "0.3.2"
  # Proprietary; the binary is not open source. See the tap LICENSE.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v0.3.2/line9-cli-v0.3.2-aarch64-apple-darwin.tar.gz"
      sha256 "bf01fd22eb6a272860bbb304b3b88ae6ce10be9e46b6bdec0a107ffef6a45bf8"
    end
    on_intel do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v0.3.2/line9-cli-v0.3.2-x86_64-apple-darwin.tar.gz"
      sha256 "ca217faa1ee741bb38586404dc2b140bb4af112ca90b68b8ba953c0a308905fd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v0.3.2/line9-cli-v0.3.2-aarch64-unknown-linux-musl.tar.gz"
      sha256 "f6d50998a6b91b1d1fb42416277c803d393a9284dfca76a05e631921e50cfb19"
    end
    on_intel do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v0.3.2/line9-cli-v0.3.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "ce39a69a52d3f5a846a8db39d728834b43c581e8f2fb981edac804750ae5df6e"
    end
  end

  def install
    # The archive's single top-level dir (line9-<tag>-<target>/) holds the
    # binary; Homebrew auto-changes into it on unpack, so install from the root.
    bin.install "line9"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/line9 --version")
  end
end
