# Generated by scripts/update-homebrew-formula.sh from release cli-v0.3.0.
# Do not edit by hand — re-run the script against a new release tag.
class Line9 < Formula
  desc "Diagrams for thinking — render Mermaid diagrams from the CLI"
  homepage "https://line9.ai"
  version "0.3.0"
  # Proprietary; the binary is not open source. See the tap LICENSE.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v0.3.0/line9-cli-v0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "f1d481db5e708139eaddf84d6451ea694ec3d421ece56a8c3e4b16b712774de1"
    end
    on_intel do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v0.3.0/line9-cli-v0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "f14edb40e62a03acbb3e8779b81ee0b5ec34f35d2366576a23d45f82c0074127"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v0.3.0/line9-cli-v0.3.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "6284dc15030ff37da3fa7c2b7181dbca069a7ab8a0cdf432b20852d68405647b"
    end
    on_intel do
      url "https://github.com/line9-ai/line9-cli/releases/download/cli-v0.3.0/line9-cli-v0.3.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "c8b2083052b46e8eb2b106cd870c00d5b1df4de55f987ad8daeeb4c4cafbbcd8"
    end
  end

  def install
    # The archive's single top-level dir (line9-<tag>-<target>/) holds the
    # binary; Homebrew auto-changes into it on unpack, so install from the root.
    bin.install "line9"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/line9 --version")
  end
end
